/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LabReservationSystem;


/**
 *
 * @author asdf0
 */
public class AssistantMain extends javax.swing.JFrame {

    /**
     * Creates new form ProfessorMain
     */
    public AssistantMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        timeTableManageButt = new javax.swing.JButton();
        manageButt = new javax.swing.JButton();
        reservationManageButt = new javax.swing.JButton();
        noticeManageButt = new javax.swing.JButton();
        userInforManageButt = new javax.swing.JButton();
        labManageButt = new javax.swing.JButton();
        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1110, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        timeTableManageButt.setBackground(new java.awt.Color(255, 255, 255));
        timeTableManageButt.setForeground(new java.awt.Color(255, 255, 255));
        timeTableManageButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtPicture/조교_시간표관리 버튼.PNG"))); // NOI18N
        timeTableManageButt.setBorderPainted(false);
        timeTableManageButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTableManageButtActionPerformed(evt);
            }
        });

        manageButt.setBackground(new java.awt.Color(255, 255, 255));
        manageButt.setForeground(new java.awt.Color(255, 255, 255));
        manageButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtPicture/조교_승인 및 초기화 관리 버튼.PNG"))); // NOI18N
        manageButt.setBorderPainted(false);
        manageButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageButtActionPerformed(evt);
            }
        });

        reservationManageButt.setBackground(new java.awt.Color(255, 255, 255));
        reservationManageButt.setForeground(new java.awt.Color(255, 255, 255));
        reservationManageButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtPicture/조교_예약 관리 버튼.PNG"))); // NOI18N
        reservationManageButt.setBorderPainted(false);
        reservationManageButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationManageButtActionPerformed(evt);
            }
        });

        noticeManageButt.setBackground(new java.awt.Color(255, 255, 255));
        noticeManageButt.setForeground(new java.awt.Color(255, 255, 255));
        noticeManageButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtPicture/조교_공지사항 및 신고관리 버튼.PNG"))); // NOI18N
        noticeManageButt.setBorderPainted(false);
        noticeManageButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeManageButtActionPerformed(evt);
            }
        });

        userInforManageButt.setBackground(new java.awt.Color(255, 255, 255));
        userInforManageButt.setForeground(new java.awt.Color(255, 255, 255));
        userInforManageButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtPicture/조교_회원정보관리 버튼.PNG"))); // NOI18N
        userInforManageButt.setBorderPainted(false);
        userInforManageButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInforManageButtActionPerformed(evt);
            }
        });

        labManageButt.setBackground(new java.awt.Color(255, 255, 255));
        labManageButt.setForeground(new java.awt.Color(255, 255, 255));
        labManageButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtPicture/조교_실습실관리 버튼.PNG"))); // NOI18N
        labManageButt.setBorderPainted(false);
        labManageButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labManageButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reservationManageButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labManageButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeTableManageButt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noticeManageButt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(110, 110, 110)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userInforManageButt)
                    .addComponent(manageButt))
                .addGap(80, 80, 80))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeTableManageButt, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(reservationManageButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userInforManageButt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labManageButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noticeManageButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1100, 620));

        TitlePanel.setBackground(new java.awt.Color(204, 204, 204));
        TitlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TitlePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TitlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitlePanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 30)); // NOI18N
        jLabel1.setText("컴퓨터소프트웨어공학과 실습실 예약 시스템");

        textField1.setEditable(false);
        textField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField1.setText("홍길동");

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setText("님");

        jLabel2.setText("(조교)");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TitlePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(TitlePanelLayout.createSequentialGroup()
                        .addContainerGap(71, Short.MAX_VALUE)
                        .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TitlePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitlePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitlePanelMouseClicked
        
    }//GEN-LAST:event_TitlePanelMouseClicked

    private void timeTableManageButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTableManageButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTableManageButtActionPerformed

    private void manageButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageButtActionPerformed

    private void reservationManageButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationManageButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationManageButtActionPerformed

    private void noticeManageButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeManageButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeManageButtActionPerformed

    private void userInforManageButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInforManageButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInforManageButtActionPerformed

    private void labManageButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labManageButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labManageButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssistantMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssistantMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssistantMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssistantMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssistantMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton labManageButt;
    private java.awt.Label label1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton manageButt;
    private javax.swing.JButton noticeManageButt;
    private javax.swing.JButton reservationManageButt;
    private java.awt.TextField textField1;
    private javax.swing.JButton timeTableManageButt;
    private javax.swing.JButton userInforManageButt;
    // End of variables declaration//GEN-END:variables
}
